# Site
repository:
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daniel R.
title: AWS DevOps Engineer
email:
website:

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username:
github_username:  nostro2
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username:
linkedin_username: 4wh3xnsr1nis
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "G-L51QN7J3M6"

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_profile_image: https://lh3.googleusercontent.com/pw/AP1GczOFh2IlIu2gZnjwNluD8iZZ7SP_GN3GcGk0H1HEkIW_YDItmXAayx70ree058Va38GtSPMp0FtqHPTOlrby4ryfI92_RMu95yRUbocUZW9XzuhLtWYBDlkn2_xD-Da-gZ95F-Nd9mYdPRJvqCXgms3VeA=w1440-h1440-s-no?authuser=0
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Dan and I'm an AWS Certified DevOps Professional that loves all things automation.

  Experienced in building and supporting customer projects on a wide range of services offered by AWS. Some of my favourite services include Lambda, EKS and Codebuild. As a fan of infrastructure as code, Terraform is my tool of choice when it comes to implementing a solution.
  
  I'm an advocate for remote working and invest that time saved commuting composing music.

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Matrixx Software
        sub_title: Senior DevOps Engineer
        caption: December 2021 - Current
        link: https://www.matrixx.com/ 
        #quote: > Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Maintaining and improving AWS infrastructure supporting CI/CD systems and internal tooling for software teams across the company. Migrated Jenkins and other build supporting services to a modern hybrid cloud cluster with terraform managed AWS resources. Architected and delivered event-based autoscaling for Jenkins workers via SQS. Built internal automation using python in AWS Lambda to: Whitelist developer IPs based on request header; Detect and delete unused AWS resources in non critical regions; Monitor and email weekly AWS cost summaries by service and region. Shadow release management processes and contribute to stability during release escalations where CI builds or pipelines fail. Drive cost and security optimizations through monitoring, automation, and operational cleanup across the AWS account.
      - layout: left
        title: Nasstar (previously KCOM)
        sub_title: DevOps Engineer
        caption: June 2018 - December 2021
        link: https://www.nasstar.com
        #quote: > Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Provisioning cloud resources for new and existing customer projects using internally maintained CloudFormation templates and developing new template features where necessary. Responsible for reviewing and merging code, maintaining current projects and handing projects over to revlevant teams via mentoring and documentation. Upholding DevOps principles with automation, deployment pipelines and immutable infrastructure while avoiding manual changes in the AWS console. Prioritising the use of AWS CloudFormation orchestrated using Python.
      - layout: left
        title: EveryCity
        sub_title: DevOps Engineer
        caption: October 2016 - June 2018
        link:
        #quote: > Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Supporting customer operations via support tickets and phone calls. Responding to alerts and escalating where necessary whilst prioritising more important incidents. Recommending infrastructure improvements and adding documentation around processes that are not already documented. On-boarding new customers via requirements capture, migrating applications to AWS and re-architecting existing infrastructure. Worked with an e-commerce customer base to scale up production environments before large events are put live.
      - layout: left
        title: Ngineered
        sub_title: DevOps Engineer
        caption: June 2015 - September 2016
        link:
        #quote: > Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Built and maintained cloud infrastructure of customers using cloud platforms like Amazon Web Services. As well as maintaining customer infrastructure, contributed to internal software projects. As part of the support duties, actively wrote documentation and built up knowledge bases as well as engage with customers.

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: AWS Certified DevOps Engineer - Professional
        caption: Issued October 2020 - Expires October 2023
      - layout: left
        title: AWS Certified Solutions Architect - Associate
        caption: Issued December 2017 - Expires December 2020
      - layout: left
        title: Cisco CCNA
        caption: Issued 2016

  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Essex
        sub_title: BSc Computer Science - 2.1
        caption: 2012 - 2015
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs



          Relevant modules include:

            `Network Engineering` `Operating Systems` `Application Programming` `Computer Security` `Mathematics for Computing`

      - layout: left
        title: Colchester Institute
        sub_title: Music Technology - Distinction
        caption: 2009 - 2012
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs

  - title: Volunteer Experience
    layout: list
    content:
      - layout: left
        title: YMCA
        sub_title: Music Tutor
        caption: 2010 - 2017
        #link: https://kcom.com
        #quote: > Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Worked closely with youth workers and volunteers to ensure young people within the local community could develop their own music related skills. Tutored young people starting bands in music improvisation as a session bass player. Involved in the planning of live music fund raisers whilst employing skills gained at BTEC to sound engineer events.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs

      Away from the office, I'm a long time Debian Linux user that spends way too much time trying to get things to run under proton.
      Guitarist of 20+ years, I love spending time at home composing music that I can perform at gigs as part of my live looping project.

      Always interested in hearing about the latest developments in green technologies and sustainable life choices.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
